services:
  # Backend Laravel
  laravel:
    build:
      context: ./backend/vendor/laravel/sail/runtimes/8.5
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000' # Valor estándar para desarrollo
    ports:
      - "8000:80"
    environment:
      LARAVEL_SAIL: 1
    volumes:
      - "./backend:/var/www/html"
    networks:
      - mi-red
    depends_on:
      - mysql

  # Base de datos MySQL
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'admin1234' # Te recomiendo usar la misma del admin para no liarte
      MYSQL_DATABASE: 'cospace_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin1234'
    volumes:
      - 'db-data:/var/lib/mysql'
    networks:
      - mi-red

  # phpMyAdmin
  phpmyadmin:
    image: 'phpmyadmin:latest'
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin1234
    networks:
      - mi-red
    depends_on:
      - mysql

  # Frontend Angular
  angular:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - "./frontend:/app"
    # Añadimos la instalación explícita de la CLI por si acaso
    command: sh -c "npm install && npm install -g @angular/cli && ng serve --host 0.0.0.0 --poll 2000"
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge

volumes:
  db-data:
    driver: local